In [1]:
import pandas as pd
import sqlite3

# SQLite dosyasının yolu
sqlite_file = "v12.gts.sqlite3.db"  # SQLite dosya adınızı buraya yazın

# SQLite bağlantısı oluştur
connection = sqlite3.connect(sqlite_file)

# SQLite dosyasındaki tabloların isimlerini öğren
tables = pd.read_sql_query("SELECT name FROM sqlite_master WHERE type='table';", connection)
print("Tablolar:")
print(tables)

# Bir tabloyu pandas DataFrame'e yükle
table_name = "madde"  # Okumak istediğiniz tablo adını buraya yazın
df = pd.read_sql_query(f"SELECT * FROM {table_name};", connection)
df

Tablolar:
            name
0          ornek
1          anlam
2  anlam_ozellik
3        atasozu
4          madde
5        ozellik
6          yazar
7  madde_atasozu

,madde_id,anlam_gor,anlam_say,birlesikler,cesit_say,cesit,cogul_mu,egik_mi,font,gosterim_tarihi,kac,kelime_no,lisan_kodu,lisan,madde_duz,madde,on_taki,ozel_mi,taki,telaffuz
0,1,0,1,None,0,0,0,0,None,None,0,14800,0,,dulavrat otu,dulavrat otu,None,0,None,None
1,2,0,2,None,1,0,0,0,None,None,0,14801,0,,dulda,dulda,None,0,None,None
2,3,0,1,None,0,1,0,0,None,2023-11-07,0,14801,0,,dulda tutmak,dulda tutmak,None,0,None,None
3,4,0,1,None,0,0,0,0,None,None,0,14802,0,,duldalama,duldalama,None,0,None,None
4,5,0,1,None,0,0,0,0,None,None,0,14803,0,,duldalamak,duldalamak,None,0,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99231,99499,0,1,,0,0,0,0,None,None,0,111598,0,,anlik olusum,anlık oluşum,None,0,,
99232,99500,0,1,,0,0,0,0,None,None,0,111599,0,,sozluksellesme,sözlükselleşme,None,0,,
99233,99501,2,1,,0,0,0,0,None,None,2,111600,11,Arapça bahār,bahar,bahar,None,0,,baha:rı
99234,99503,0,1,,0,0,0,0,None,None,0,111602,13,Fransızca frigidité,frijidite,frijidite,None,0,,
99235,99504,0,1,,0,0,0,0,None,None,0,111603,0,,kara yazililik,kara yazılılık,None,0,ğı,

In [ ]:
for table_name in tables["name"]:
    df = pd.read_sql_query(f"SELECT * FROM {table_name};", connection)
    print(f"\n{table_name} tablosu:", df.shape)
    # save to csv
    file_name = f"{table_name}.csv"
    df.to_csv(file_name, index=False, encoding="utf-8")
    print(df.head(2))

In [6]:
file_names = ['sozluk/ornek.csv',
 'sozluk/anlam.csv',
 'sozluk/anlam_ozellik.csv',
 'sozluk/atasozu.csv',
 'sozluk/madde.csv',
 'sozluk/ozellik.csv',
 'sozluk/yazar.csv',
 'sozluk/madde_atasozu.csv']

['sozluk/ornek.csv',
 'sozluk/anlam.csv',
 'sozluk/anlam_ozellik.csv',
 'sozluk/atasozu.csv',
 'sozluk/madde.csv',
 'sozluk/ozellik.csv',
 'sozluk/yazar.csv',
 'sozluk/madde_atasozu.csv']

In [9]:
ornek = pd.read_csv(file_names[0])
anlam = pd.read_csv(file_names[1])
anlam_ozellik = pd.read_csv(file_names[2])
atasozu = pd.read_csv(file_names[3])
madde = pd.read_csv(file_names[4])
ozellik = pd.read_csv(file_names[5])
yazar = pd.read_csv(file_names[6])
madde_atasozu = pd.read_csv(file_names[7])
anlam

/var/folders/gs/crm1zcvj00j1kl0l1lvz4qf40000gn/T/ipykernel_8336/173138693.py:5: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  madde = pd.read_csv(file_names[4])

,anlam_id,anlam_sira,anlam,fiil,gos,madde_id,tipkes
0,0,1,"Bir topluluk karşısında etkili, açık, düzgün k...",0,0,28579,0
1,1,1,Acınılmak işi,0,0,6142,0
2,2,1,Tuhaf kimse,0,0,6143,0
3,3,2,"Tuhaf, alışılmadık, garip şey",0,0,6143,0
4,4,1,Açık fikirli olma durumu; açık görüşlülük,0,0,6144,0
...,...,...,...,...,...,...,...
133032,747088,5,► taşaklı,0,0,42673,1
133033,747089,1,► baharat,0,0,99501,1
133034,747092,3,"Kendini hasta veya yorgun, bitkin hissetmek",0,0,38411,1
133035,747093,1,Kadında cinsel isteksizlik,0,0,99503,1
133036,747094,1,Kara yazılı olma durumu,0,0,99504,1